
export const ProductDetails = [
    {
        id: 1,
        title: "Samsung",
        images: "img/mobile_one.jpg",
        company: "Google",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 10,
        count: 0,
        total: 0,
    },
    {
        id: 2,
        title: "Nokia",
        images: "img/mobile_two.jpg",
        company: "Bell",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 3200,
        count: 0,
        total: 0,
    },
    {
        id: 3,
        title: "Netfix",
        images: "img/mobile_three.jpg",
        company: "Google",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 2500,
        count: 0,
        total: 0,
    },
    {
        id: 4,
        title: "Fxd",
        images: "img/mobile_four.jpg",
        company: "Google",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 2500,
        count: 0,
        total: 0,
    },
    {
        id: 5,
        title: "Samsung",
        images: "img/mobile_one.jpg",
        company: "Google",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 2200,
        count: 0,
        total: 0,
    },
    {
        id: 6,
        title: "Nokia",
        images: "img/mobile_two.jpg",
        company: "Bell",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 3200,
        count: 0,
        total: 0,
    },
    {
        id: 7,
        title: "Netfix",
        images: "img/mobile_three.jpg",
        company: "Google",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 2500,
        count: 0,
        total: 0,
    },
    {
        id: 8,
        title: "Fxd",
        images: "img/mobile_four.jpg",
        company: "Google",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 2500,
        count: 0,
        total: 0,
    }
];
export const DetailPages = [
    {
        id: 1,
        title: "detail",
        images: "img/mobile_four.jpg",
        company: "Google",
        info: "In publishing and graphic design Lorem ipsum is a placeholder text commonly  used to demonstrate the visual form of a document  or a typeface without relying on meaningful content.Wikipedia",
        inCart: false,
        price: 2500,
        count: 0,
        total: 0,
    }
]